# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.cache/wt [current_project]
set_property parent.project_path /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/new/Audio_Box.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/imports/new/ClockDivider.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/imports/new/Color_Box.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/imports/new/Counter.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/new/Debouncer.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/new/Game_Controller.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/imports/new/Mux.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/imports/new/VGA_Controller.v
  /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/sources_1/imports/new/Wrapper.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/constrs_1/imports/Simon_Says/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files /home/brandon/Documents/Vivado_Projects/Simon_Says/Simon_Says.srcs/constrs_1/imports/Simon_Says/Nexys4DDR_Master.xdc]


synth_design -top Wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
